# Generated by Django 4.2.27 on 2025-12-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_momo_api_key_tenant_momo_enabled_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this metrics snapshot')),
                ('mrr_cents', models.BigIntegerField(default=0, help_text='Monthly Recurring Revenue in cents')),
                ('arr_cents', models.BigIntegerField(default=0, help_text='Annual Recurring Revenue in cents (MRR * 12)')),
                ('total_revenue_cents', models.BigIntegerField(default=0, help_text='Total revenue collected to date in cents')),
                ('new_revenue_cents', models.BigIntegerField(default=0, help_text='Revenue generated on this date in cents')),
                ('total_customers', models.IntegerField(default=0, help_text='Total active customers')),
                ('active_subscribers', models.IntegerField(default=0, help_text='Number of active subscriptions')),
                ('new_subscribers', models.IntegerField(default=0, help_text='New subscribers on this date')),
                ('churned_subscribers', models.IntegerField(default=0, help_text='Subscribers who churned on this date')),
                ('successful_payments', models.IntegerField(default=0, help_text='Number of successful payments on this date')),
                ('failed_payments', models.IntegerField(default=0, help_text='Number of failed payments on this date')),
                ('successful_payments_amount_cents', models.BigIntegerField(default=0, help_text='Total amount from successful payments in cents')),
                ('refunds_count', models.IntegerField(default=0, help_text='Number of refunds on this date')),
                ('refunds_amount_cents', models.BigIntegerField(default=0, help_text='Total refund amount in cents')),
                ('deferred_revenue_cents', models.BigIntegerField(default=0, help_text='Revenue collected but not yet earned (prepayments)')),
                ('recognized_revenue_cents', models.BigIntegerField(default=0, help_text='Revenue that has been earned on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Metric',
                'verbose_name_plural': 'Tenant Metrics',
                'db_table': 'tenant_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', '-date'], name='tenant_metr_tenant__cc4284_idx'), models.Index(fields=['date'], name='tenant_metr_date_35eaee_idx')],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CohortAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_month', models.DateField(help_text='First day of the month when customers signed up')),
                ('period', models.IntegerField(help_text='Number of months since cohort_month (0 = first month)')),
                ('customers_count', models.IntegerField(default=0, help_text='Number of customers from this cohort still active')),
                ('original_customers_count', models.IntegerField(default=0, help_text='Original number of customers in this cohort')),
                ('revenue_cents', models.BigIntegerField(default=0, help_text='Revenue from this cohort in this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'cohort_analysis',
                'ordering': ['cohort_month', 'period'],
                'indexes': [models.Index(fields=['tenant', 'cohort_month'], name='cohort_anal_tenant__3fd1c4_idx')],
                'unique_together': {('tenant', 'cohort_month', 'period')},
            },
        ),
    ]
