# Generated by Django 4.2.27 on 2025-12-08 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('api_key_public', models.CharField(db_index=True, help_text='Public API key for live mode (pk_live_xxx)', max_length=255, unique=True)),
                ('api_key_secret', models.CharField(db_index=True, help_text='Secret API key for live mode (sk_live_xxx)', max_length=255, unique=True)),
                ('api_key_test_public', models.CharField(db_index=True, help_text='Public API key for test mode (pk_test_xxx)', max_length=255, unique=True)),
                ('api_key_test_secret', models.CharField(db_index=True, help_text='Secret API key for test mode (sk_test_xxx)', max_length=255, unique=True)),
                ('stripe_connect_account_id', models.CharField(blank=True, db_index=True, help_text='Stripe Connect account ID for this tenant', max_length=255, null=True, unique=True)),
                ('stripe_connect_status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('restricted', 'Restricted')], db_index=True, default='pending', max_length=20)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Platform fee percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('webhook_url', models.URLField(blank=True, help_text='URL to send webhook events to', max_length=500, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook signature verification (whsec_xxx)', max_length=255, null=True)),
                ('branding_json', models.JSONField(blank=True, default=dict, help_text='JSON object containing logo URL, primary color, secondary color, etc.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_test_mode', models.BooleanField(db_index=True, default=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the tenant')),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(help_text='Hashed password', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('developer', 'Developer')], db_index=True, default='developer', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['company_name', 'is_active'], name='tenants_company_b47635_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['email', 'is_active'], name='tenants_email_46e4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subscription_tier', 'is_active'], name='tenants_subscri_41da39_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'email'], name='tenant_user_tenant__444ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_user_tenant__068a9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'email')},
        ),
    ]
