# Generated by Django 4.2.27 on 2025-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantplan',
            new_name='tenant_plan_tenant__a1cd6f_idx',
            old_name='tenant_plan_tenant_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantplan',
            new_name='tenant_plan_tenant__bd6fbd_idx',
            old_name='tenant_plan_tenant_billing_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantplan',
            new_name='tenant_plan_stripe__b4a7ad_idx',
            old_name='tenant_plan_stripe_product_idx',
        ),
        migrations.AlterField(
            model_name='tenantplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
