# Generated by Django 4.2.27 on 2025-12-10 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rename_tenant_plan_tenant_is_active_idx_tenant_plan_tenant__a1cd6f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, help_text="Customer's email address", max_length=254)),
                ('full_name', models.CharField(blank=True, help_text="Customer's full name", max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=50, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, help_text="Stripe customer ID in tenant's connected account", max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM medium parameter', max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=255, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the customer')),
                ('tenant', models.ForeignKey(help_text='The tenant this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, help_text='Stripe subscription ID', max_length=255, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID used to create this subscription', max_length=255, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], db_index=True, default='incomplete', help_text='Current subscription status', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of the current billing period', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, help_text='End of the current billing period', null=True)),
                ('trial_start', models.DateTimeField(blank=True, help_text='Start of the trial period', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='End of the trial period', null=True)),
                ('cancel_at_period_end', models.BooleanField(db_index=True, default=False, help_text='Whether subscription will be canceled at period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the subscription was canceled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Number of seats/units for this subscription', validators=[django.core.validators.MinValueValidator(1)])),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the subscription')),
                ('customer', models.ForeignKey(help_text='The customer who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenantcustomer')),
                ('plan', models.ForeignKey(help_text='The plan this subscription is for', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.tenantplan')),
                ('tenant', models.ForeignKey(help_text='The tenant this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='tenant_subs_tenant__11bdb5_idx'), models.Index(fields=['customer', 'status'], name='tenant_subs_custome_63921d_idx'), models.Index(fields=['plan', 'status'], name='tenant_subs_plan_id_23b228_idx'), models.Index(fields=['tenant', 'current_period_end'], name='tenant_subs_tenant__63ce4d_idx'), models.Index(fields=['status', 'cancel_at_period_end'], name='tenant_subs_status_46e354_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'email'], name='tenant_cust_tenant__420f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'created_at'], name='tenant_cust_tenant__76fd18_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['stripe_customer_id'], name='tenant_cust_stripe__9f4040_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantcustomer',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='unique_customer_email_per_tenant'),
        ),
    ]
