# Generated by Django 4.2.27 on 2025-12-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantcustomer_tenantsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, help_text='Type of webhook event (e.g., subscription.created)', max_length=100)),
                ('payload_json', models.JSONField(help_text='Full event payload to send')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current delivery status', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Number of delivery attempts')),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP response code from last delivery attempt', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response body from last delivery attempt', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the webhook was first sent', null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, db_index=True, help_text='When the webhook was successfully delivered', null=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate event processing', max_length=255, unique=True)),
                ('tenant', models.ForeignKey(help_text='The tenant to send this webhook to', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_webhook_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.IntegerField(help_text='Payment amount in cents')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', help_text='Current payment status', max_length=20)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'Mobile Money'), ('manual', 'Manual')], db_index=True, default='stripe', help_text='Payment provider', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, help_text='Payment ID from the provider (e.g., Stripe payment intent ID)', max_length=255, null=True)),
                ('platform_fee_cents', models.IntegerField(default=0, help_text='Platform fee amount in cents')),
                ('tenant_net_amount_cents', models.IntegerField(help_text='Net amount received by tenant after platform fee (in cents)')),
                ('failure_code', models.CharField(blank=True, help_text='Error code from payment provider', max_length=100, null=True)),
                ('failure_message', models.TextField(blank=True, help_text='Error message from payment provider', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('invoice_pdf_url', models.URLField(blank=True, help_text='URL to invoice PDF', max_length=500, null=True)),
                ('receipt_url', models.URLField(blank=True, help_text='URL to payment receipt', max_length=500, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('customer', models.ForeignKey(blank=True, help_text='The customer who made this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tenants.tenantcustomer')),
                ('subscription', models.ForeignKey(blank=True, help_text='The subscription this payment is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tenants.tenantsubscription')),
                ('tenant', models.ForeignKey(help_text='The tenant this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.IntegerField(help_text='Which attempt this log represents (1, 2, 3, etc.)')),
                ('request_url', models.URLField(help_text='URL the webhook was sent to', max_length=500)),
                ('request_headers', models.JSONField(default=dict, help_text='Request headers sent')),
                ('request_body', models.JSONField(help_text='Request body sent')),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP response code', null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='Response headers received')),
                ('response_body', models.TextField(blank=True, help_text='Response body received', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('webhook_event', models.ForeignKey(help_text='The webhook event this log is for', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tenants.tenantwebhookevent')),
            ],
            options={
                'db_table': 'tenant_webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook_event', 'attempt_number'], name='tenant_webh_webhook_cd7f37_idx'), models.Index(fields=['created_at'], name='tenant_webh_created_dd42f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenantwebhookevent',
            index=models.Index(fields=['tenant', 'status'], name='tenant_webh_tenant__70fc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantwebhookevent',
            index=models.Index(fields=['event_type', 'created_at'], name='tenant_webh_event_t_25ece6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantwebhookevent',
            index=models.Index(fields=['status', 'attempts'], name='tenant_webh_status_380348_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantwebhookevent',
            index=models.Index(fields=['tenant', 'event_type', 'created_at'], name='tenant_webh_tenant__c441a1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['tenant', 'status'], name='tenant_paym_tenant__756b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['customer', 'status'], name='tenant_paym_custome_4de0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['subscription', 'created_at'], name='tenant_paym_subscri_5dc234_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='tenant_paym_provide_4b944e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['status', 'created_at'], name='tenant_paym_status_2fd109_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id__isnull', False)), fields=('provider', 'provider_payment_id'), name='unique_provider_payment'),
        ),
    ]
