# Generated by Django 4.2.27 on 2025-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantwebhookevent_tenantpayment_tenantwebhooklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='momo_api_key',
            field=models.CharField(blank=True, help_text='Encrypted MTN Mobile Money API key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='momo_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether Mobile Money payments are enabled for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='momo_merchant_id',
            field=models.CharField(blank=True, db_index=True, help_text='MTN Mobile Money merchant ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='momo_provider',
            field=models.CharField(blank=True, db_index=True, help_text='MoMo provider: mtn, vodafone, airteltigo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='momo_sandbox_mode',
            field=models.BooleanField(default=True, help_text='Whether to use Mobile Money sandbox environment'),
        ),
    ]
