# Generated by Django 4.2.27 on 2025-12-12 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_momo_api_key_tenant_momo_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='platform_fee_fixed_cents',
            field=models.IntegerField(default=50, help_text='Fixed platform fee in cents (e.g., 50 = $0.50)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
