# Generated by Django 4.2.27 on 2025-12-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_platform_fee_fixed_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='paystack_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether Paystack payments are enabled for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paystack_public_key',
            field=models.CharField(blank=True, help_text='Paystack public key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paystack_secret_key',
            field=models.CharField(blank=True, help_text='Paystack secret key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paystack_test_mode',
            field=models.BooleanField(default=True, help_text='Whether to use Paystack test mode'),
        ),
    ]
