# Generated by Django 4.2.27 on 2025-12-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_paystack_enabled_tenant_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='paystack_default_currency',
            field=models.CharField(choices=[('ngn', 'NGN'), ('ghs', 'GHS'), ('zar', 'ZAR'), ('usd', 'USD')], default='ghs', help_text='Default currency for Paystack transactions', max_length=3),
        ),
        migrations.AlterField(
            model_name='tenantplan',
            name='currency',
            field=models.CharField(choices=[('ngn', 'NGN'), ('usd', 'USD'), ('ghs', 'GHS'), ('zar', 'ZAR'), ('eur', 'EUR'), ('gbp', 'GBP'), ('cad', 'CAD'), ('aud', 'AUD')], default='ghs', help_text='Three-letter ISO currency code', max_length=3),
        ),
    ]
