# Generated by Django 4.2.27 on 2025-12-12 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0007_tenant_platform_fee_fixed_cents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_days', models.IntegerField(default=0)),
                ('success_url', models.URLField(max_length=500)),
                ('cancel_url', models.URLField(max_length=500)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('momo_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'Mobile Money')], default='stripe', max_length=20)),
                ('amount_cents', models.BigIntegerField(help_text='Gross amount charged to customer')),
                ('platform_fee_cents', models.BigIntegerField(help_text="Platform's revenue from this transaction")),
                ('tenant_net_amount_cents', models.BigIntegerField(help_text='Amount tenant receives (gross - fee)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='billing.billingplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'checkout_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='checkout_se_tenant__e9e993_idx'), models.Index(fields=['tenant', 'created_at'], name='checkout_se_tenant__8a9dba_idx'), models.Index(fields=['customer_email'], name='checkout_se_custome_6fa9b0_idx')],
            },
        ),
    ]
