# Generated by Django 4.2.27 on 2025-12-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='paystack_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'Mobile Money'), ('paystack', 'Paystack')], default='stripe', max_length=20),
        ),
    ]
