# Generated by Django 4.2.27 on 2025-12-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_paystack_enabled_tenant_paystack_public_key_and_more'),
        ('checkout', '0002_checkoutsession_paystack_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='tenants.tenantplan'),
        ),
    ]
